import Stripe from 'stripe';
import { TaxAddressError } from '../payments';
import type { PaymentProviderAdapter, PaymentReferences, TaxCalculation, TaxCalculationParams, ValidatedWebhookEvent } from '../payments';

export interface StripeAdapterConfig {
  secretKey: string;
  webhookSecret?: string;
}

/** The parts of the address the shopper filled in. Stripe reads an empty string as clearing a field. */
function stripeTaxAddress(address: TaxCalculationParams['address']) {
  const result: Stripe.Tax.CalculationCreateParams.CustomerDetails.Address = { country: address.country };
  const parts = { line1: address.line1, line2: address.line2, city: address.city, state: address.state,
    postal_code: address.postalCode };
  for (const [key, value] of Object.entries(parts) as Array<[keyof typeof parts, string | undefined]>) {
    if (typeof value === 'string' && value.trim()) result[key] = value.trim();
  }
  return result;
}

/**
 * The coupon of an order's checkout has an id derived from the order id, so it can be deleted
 * later without storing it. Order ids are generated by the server as `ord_` plus a UUID.
 */
export function checkoutCouponId(orderId: string): string {
  if (!/^[A-Za-z0-9_-]{1,120}$/.test(orderId)) throw new Error('Order id cannot name a checkout coupon');
  return `${orderId}_discount`;
}

export class StripePaymentAdapter implements PaymentProviderAdapter {
  public readonly providerId = 'stripe';
  private stripe: Stripe;
  private config: StripeAdapterConfig;

  constructor(config: StripeAdapterConfig) {
    this.config = config;
    // Stripe >= v12 uses fetch by default in Edge environments
    this.stripe = new Stripe(config.secretKey, {
      apiVersion: '2026-08-26.dahlia',
      timeout: 15_000,
      maxNetworkRetries: 1,
      appInfo: {
        name: 'Talisman CMS E-Commerce Plugin',
        version: '0.0.1',
      },
    });
  }

  async createCheckoutSession(params: {
    orderId: string;
    currency: string;
    items: Array<{ name: string; description?: string; priceCents: number; quantity: number }>;
    customerEmail?: string;
    successUrl: string;
    cancelUrl: string;
    metadata?: Record<string, string>;
    creditApplied?: number;
    discountApplied?: number;
    giftCardApplied?: number;
    shipping?: { label: string; amount: number; description?: string };
    tax?: { amount: number };
  }): Promise<{ url: string; providerSessionId: string }> {
    const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = params.items.map(item => ({
      price_data: {
        currency: params.currency,
        product_data: {
          name: item.name,
          description: item.description,
        },
        unit_amount: item.priceCents,
      },
      quantity: item.quantity,
    }));
    // Shipping is a line of its own, so the one coupon below still covers every adjustment and the
    // session's total is the order's.
    if (params.shipping && params.shipping.amount > 0) {
      lineItems.push({
        price_data: {
          currency: params.currency,
          product_data: {
            name: params.shipping.label,
            description: params.shipping.description,
          },
          unit_amount: params.shipping.amount,
        },
        quantity: 1,
      });
    }
    // Exclusive tax was calculated with Stripe Tax before the session, so it is a line too and
    // automatic_tax stays off: the session charges exactly the order's total.
    if (params.tax && params.tax.amount > 0) {
      lineItems.push({
        price_data: {
          currency: params.currency,
          product_data: { name: 'Tax' },
          unit_amount: params.tax.amount,
        },
        quantity: 1,
      });
    }

    const totalDiscount = (params.creditApplied ?? 0) + (params.discountApplied ?? 0)
      + (params.giftCardApplied ?? 0);
    // The session and its coupon end together: the coupon is redeemable once, only by this
    // order's session, and only until the session expires. Stripe needs a session to live at
    // least 30 minutes; the extra minute covers the coupon request that comes first, and the
    // total stays under the 35 minutes after which a stale checkout preparation is released.
    const expiresAt = Math.floor(Date.now() / 1000) + 31 * 60;
    const coupon = totalDiscount ? await this.stripe.coupons.create({
      id: checkoutCouponId(params.orderId),
      amount_off: totalDiscount,
      currency: params.currency,
      duration: 'once',
      max_redemptions: 1,
      redeem_by: expiresAt,
      name: params.giftCardApplied ? 'Gift card and checkout adjustments' : 'Promotion and store credit',
    }, { idempotencyKey: `${params.orderId}:discount` }) : null;

    const session = await this.stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: lineItems,
      mode: 'payment',
      // Confirmation and refunds compare the amount and currency with the order, so the buyer is
      // never shown another currency (Adaptive Pricing), whatever the account's dashboard setting.
      currency: params.currency,
      adaptive_pricing: { enabled: false },
      expires_at: expiresAt,
      success_url: params.successUrl,
      cancel_url: params.cancelUrl,
      customer_email: params.customerEmail,
      discounts: coupon ? [{ coupon: coupon.id }] : undefined,
      client_reference_id: params.orderId,
      metadata: {
        orderId: params.orderId,
        ...params.metadata,
      },
      // The charge, its refunds and disputes carry the store's reference, so a webhook event for a
      // payment the store has not recorded yet can be told apart from one of another integration.
      payment_intent_data: { metadata: params.metadata?.giftCardPurchaseId
        ? { giftCardPurchaseId: params.metadata.giftCardPurchaseId } : { orderId: params.orderId } },
    }, { idempotencyKey: params.orderId });

    if (!session.url) {
      throw new Error('Failed to create Stripe checkout session URL');
    }

    return {
      url: session.url,
      providerSessionId: session.id,
    };
  }

  async validateWebhook(payload: string, signature: string, secret?: string): Promise<ValidatedWebhookEvent> {
    const webhookSecret = secret || this.config.webhookSecret;
    if (!webhookSecret) {
      throw new Error('Stripe webhook secret is not configured.');
    }

    try {
      const event = await this.stripe.webhooks.constructEventAsync(
        payload,
        signature,
        webhookSecret
      );

      return {
        type: event.type,
        data: event.data.object,
        id: event.id,
        created: event.created,
        rawEvent: event,
      };
    } catch (err: any) {
      throw new Error(`Webhook Error: ${err.message}`);
    }
  }

  async expireCheckoutSession(sessionId: string): Promise<void> {
    await this.stripe.checkout.sessions.expire(sessionId);
  }

  async discardCheckoutDiscount(orderId: string): Promise<void> {
    try {
      await this.stripe.coupons.del(checkoutCouponId(orderId));
    } catch (error: any) {
      // An order without a coupon, or one already deleted, has nothing left to discard.
      if (error?.code === 'resource_missing' || error?.statusCode === 404) return;
      throw error;
    }
  }

  async getCheckoutSession(sessionId: string) {
    const session = await this.stripe.checkout.sessions.retrieve(sessionId);
    return {
      status: session.status,
      url: session.url,
      paymentStatus: session.payment_status,
      amountTotal: session.amount_total,
      currency: session.currency,
      paymentIntentId: typeof session.payment_intent === 'string' ? session.payment_intent : null,
      customerEmail: session.customer_details?.email ?? session.customer_email,
    };
  }

  async getPaymentReferences(paymentIntentId: string): Promise<PaymentReferences | null> {
    try {
      const { metadata } = await this.stripe.paymentIntents.retrieve(paymentIntentId);
      return { orderId: metadata?.orderId ?? null, giftCardPurchaseId: metadata?.giftCardPurchaseId ?? null };
    } catch (error: any) {
      // A payment of another Stripe account or mode.
      if (error?.code === 'resource_missing' || error?.statusCode === 404) return null;
      throw error;
    }
  }

  async getRefundStatus(paymentIntentId: string): Promise<'none' | 'partial' | 'full'> {
    // A Checkout payment's successful charge is the intent's latest one, and it carries the refunds.
    const intent = await this.stripe.paymentIntents.retrieve(paymentIntentId, { expand: ['latest_charge'] });
    const charge = intent.latest_charge && typeof intent.latest_charge === 'object' ? intent.latest_charge : null;
    if (!charge?.amount_refunded) return 'none';
    return charge.refunded ? 'full' : 'partial';
  }

  async getDisputeStatus(paymentIntentId: string): Promise<'none' | 'open' | 'lost'> {
    const disputes = await this.stripe.disputes.list({ payment_intent: paymentIntentId, limit: 10 });
    if (disputes.data.some((dispute) => dispute.status === 'lost')) return 'lost';
    // Won, prevented and closed inquiries are settled; any other status is still open.
    const settled = new Set(['won', 'prevented', 'warning_closed']);
    return disputes.data.some((dispute) => !settled.has(dispute.status)) ? 'open' : 'none';
  }

  async calculateTax(params: TaxCalculationParams): Promise<TaxCalculation> {
    const input: Stripe.Tax.CalculationCreateParams = {
      currency: params.currency,
      line_items: params.lines.map((line) => ({
        amount: line.amount,
        quantity: line.quantity,
        reference: line.reference,
        tax_behavior: params.behavior,
        ...((line.taxCode ?? params.taxCode) ? { tax_code: line.taxCode ?? params.taxCode ?? undefined } : {}),
      })),
      customer_details: { address: stripeTaxAddress(params.address), address_source: params.addressSource },
    };
    if (params.shippingAmount > 0) {
      input.shipping_cost = { amount: params.shippingAmount, tax_behavior: params.behavior };
    }
    if (params.shipFromCountry) input.ship_from_details = { address: { country: params.shipFromCountry } };

    let calculation: Stripe.Tax.Calculation;
    try {
      calculation = await this.stripe.tax.calculations.create(input);
    } catch (error) {
      // Stripe Tax cannot place the address, which the shopper can correct.
      if ((error as { code?: unknown } | null)?.code === 'customer_tax_location_invalid') {
        throw new TaxAddressError(undefined, { cause: error });
      }
      throw error;
    }
    if (!calculation.id) throw new Error('Stripe Tax returned a calculation without an id');
    return {
      id: calculation.id,
      amountTotal: calculation.amount_total,
      taxAmountExclusive: calculation.tax_amount_exclusive,
      taxAmountInclusive: calculation.tax_amount_inclusive,
    };
  }

  async recordTaxTransaction(params: { orderId: string; calculationId: string; postedAt?: number }) {
    const transaction = await this.stripe.tax.transactions.createFromCalculation({
      calculation: params.calculationId,
      reference: params.orderId,
      ...(params.postedAt ? { posted_at: params.postedAt } : {}),
    }, { idempotencyKey: `tax-transaction:${params.orderId}` });
    return { transactionId: transaction.id };
  }

  async reverseTaxTransaction(params: { orderId: string; transactionId: string; amount: number; reference: string }) {
    // A flat amount, tax included, which Stripe spreads over the transaction's lines and shipping.
    // Stripe expects it negative.
    const reversal = await this.stripe.tax.transactions.createReversal({
      mode: 'partial',
      original_transaction: params.transactionId,
      reference: params.reference,
      flat_amount: -params.amount,
    }, { idempotencyKey: params.reference });
    return { reversalId: reversal.id };
  }
}
