import Stripe from 'stripe';
import type { PaymentProviderAdapter, ValidatedWebhookEvent } from '../payments';

export interface StripeAdapterConfig {
  secretKey: string;
  webhookSecret?: string;
}

/**
 * The coupon of an order's checkout has an id derived from the order id, so it can be deleted
 * later without storing it. Order ids are generated by the server as `ord_` plus a UUID.
 */
export function checkoutCouponId(orderId: string): string {
  if (!/^[A-Za-z0-9_-]{1,120}$/.test(orderId)) throw new Error('Order id cannot name a checkout coupon');
  return `${orderId}_discount`;
}

export class StripePaymentAdapter implements PaymentProviderAdapter {
  public readonly providerId = 'stripe';
  private stripe: Stripe;
  private config: StripeAdapterConfig;

  constructor(config: StripeAdapterConfig) {
    this.config = config;
    // Stripe >= v12 uses fetch by default in Edge environments
    this.stripe = new Stripe(config.secretKey, {
      apiVersion: '2026-08-26.dahlia',
      timeout: 15_000,
      maxNetworkRetries: 1,
      appInfo: {
        name: 'Talisman CMS E-Commerce Plugin',
        version: '0.0.1',
      },
    });
  }

  async createCheckoutSession(params: {
    orderId: string;
    currency: string;
    items: Array<{ name: string; description?: string; priceCents: number; quantity: number }>;
    customerEmail?: string;
    successUrl: string;
    cancelUrl: string;
    metadata?: Record<string, string>;
    creditApplied?: number;
    discountApplied?: number;
    giftCardApplied?: number;
  }): Promise<{ url: string; providerSessionId: string }> {
    const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = params.items.map(item => ({
      price_data: {
        currency: params.currency,
        product_data: {
          name: item.name,
          description: item.description,
        },
        unit_amount: item.priceCents,
      },
      quantity: item.quantity,
    }));

    const totalDiscount = (params.creditApplied ?? 0) + (params.discountApplied ?? 0)
      + (params.giftCardApplied ?? 0);
    // The session and its coupon end together: the coupon is redeemable once, only by this
    // order's session, and only until the session expires. Stripe needs a session to live at
    // least 30 minutes; the extra minute covers the coupon request that comes first, and the
    // total stays under the 35 minutes after which a stale checkout preparation is released.
    const expiresAt = Math.floor(Date.now() / 1000) + 31 * 60;
    const coupon = totalDiscount ? await this.stripe.coupons.create({
      id: checkoutCouponId(params.orderId),
      amount_off: totalDiscount,
      currency: params.currency,
      duration: 'once',
      max_redemptions: 1,
      redeem_by: expiresAt,
      name: params.giftCardApplied ? 'Gift card and checkout adjustments' : 'Promotion and store credit',
    }, { idempotencyKey: `${params.orderId}:discount` }) : null;

    const session = await this.stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: lineItems,
      mode: 'payment',
      // Confirmation and refunds compare the amount and currency with the order, so the buyer is
      // never shown another currency (Adaptive Pricing), whatever the account's dashboard setting.
      currency: params.currency,
      adaptive_pricing: { enabled: false },
      expires_at: expiresAt,
      success_url: params.successUrl,
      cancel_url: params.cancelUrl,
      customer_email: params.customerEmail,
      discounts: coupon ? [{ coupon: coupon.id }] : undefined,
      client_reference_id: params.orderId,
      metadata: {
        orderId: params.orderId,
        ...params.metadata,
      },
    }, { idempotencyKey: params.orderId });

    if (!session.url) {
      throw new Error('Failed to create Stripe checkout session URL');
    }

    return {
      url: session.url,
      providerSessionId: session.id,
    };
  }

  async validateWebhook(payload: string, signature: string, secret?: string): Promise<ValidatedWebhookEvent> {
    const webhookSecret = secret || this.config.webhookSecret;
    if (!webhookSecret) {
      throw new Error('Stripe webhook secret is not configured.');
    }

    try {
      const event = await this.stripe.webhooks.constructEventAsync(
        payload,
        signature,
        webhookSecret
      );

      return {
        type: event.type,
        data: event.data.object,
        rawEvent: event,
      };
    } catch (err: any) {
      throw new Error(`Webhook Error: ${err.message}`);
    }
  }

  async expireCheckoutSession(sessionId: string): Promise<void> {
    await this.stripe.checkout.sessions.expire(sessionId);
  }

  async discardCheckoutDiscount(orderId: string): Promise<void> {
    try {
      await this.stripe.coupons.del(checkoutCouponId(orderId));
    } catch (error: any) {
      // An order without a coupon, or one already deleted, has nothing left to discard.
      if (error?.code === 'resource_missing' || error?.statusCode === 404) return;
      throw error;
    }
  }

  async getCheckoutSession(sessionId: string) {
    const session = await this.stripe.checkout.sessions.retrieve(sessionId);
    return {
      status: session.status,
      url: session.url,
      paymentStatus: session.payment_status,
      amountTotal: session.amount_total,
      currency: session.currency,
      paymentIntentId: typeof session.payment_intent === 'string' ? session.payment_intent : null,
      customerEmail: session.customer_details?.email ?? session.customer_email,
    };
  }

  async getDisputeStatus(paymentIntentId: string): Promise<'none' | 'open' | 'lost'> {
    const disputes = await this.stripe.disputes.list({ payment_intent: paymentIntentId, limit: 10 });
    if (disputes.data.some((dispute) => dispute.status === 'lost')) return 'lost';
    // Won, prevented and closed inquiries are settled; any other status is still open.
    const settled = new Set(['won', 'prevented', 'warning_closed']);
    return disputes.data.some((dispute) => !settled.has(dispute.status)) ? 'open' : 'none';
  }
}
