name = "talisman-cms-playground"
main = "./src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/10 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "galaxy_cms_local"
database_id = "local-d1"
migrations_dir = "node_modules/.talisman-cms/migrations"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "talisman-cms-media"

[images]
binding = "IMAGES"

[[kv_namespaces]]
binding = "KV"
id = "local-kv"
