/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as GlobalsRouteImport } from './routes/globals'
import { Route as MediaRouteImport } from './routes/media'
import { Route as UsersRouteImport } from './routes/users'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CommerceIndexRouteImport } from './routes/commerce/index'
import { Route as ExtensionsExtensionPathRouteImport } from './routes/extensions/$extensionPath'
import { Route as GlobalsIndexRouteImport } from './routes/globals/index'
import { Route as GlobalsSlugRouteImport } from './routes/globals/$slug'
import { Route as GlobalsNewRouteImport } from './routes/globals/new'
import { Route as CollectionsSlugIndexRouteImport } from './routes/collections/$slug/index'
import { Route as CollectionsSlugEntryIdRouteImport } from './routes/collections/$slug/$entryId'
import { Route as CommerceSlugIndexRouteImport } from './routes/commerce/$slug/index'
import { Route as CommerceSlugEntryIdRouteImport } from './routes/commerce/$slug/$entryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalsRoute = GlobalsRouteImport.update({
  id: '/globals',
  path: '/globals',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CommerceIndexRoute = CommerceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommerceRoute,
} as any)
const ExtensionsExtensionPathRoute = ExtensionsExtensionPathRouteImport.update({
  id: '/extensions/$extensionPath',
  path: '/extensions/$extensionPath',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalsIndexRoute = GlobalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlobalsRoute,
} as any)
const GlobalsSlugRoute = GlobalsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GlobalsRoute,
} as any)
const GlobalsNewRoute = GlobalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GlobalsRoute,
} as any)
const CollectionsSlugIndexRoute = CollectionsSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsSlugEntryIdRoute = CollectionsSlugEntryIdRouteImport.update({
  id: '/$slug/$entryId',
  path: '/$slug/$entryId',
  getParentRoute: () => CollectionsRoute,
} as any)
const CommerceSlugIndexRoute = CommerceSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => CommerceRoute,
} as any)
const CommerceSlugEntryIdRoute = CommerceSlugEntryIdRouteImport.update({
  id: '/$slug/$entryId',
  path: '/$slug/$entryId',
  getParentRoute: () => CommerceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/commerce': typeof CommerceRouteWithChildren
  '/globals': typeof GlobalsRouteWithChildren
  '/media': typeof MediaRoute
  '/users': typeof UsersRoute
  '/extensions/$extensionPath': typeof ExtensionsExtensionPathRoute
  '/globals/$slug': typeof GlobalsSlugRoute
  '/globals/new': typeof GlobalsNewRoute
  '/collections/': typeof CollectionsIndexRoute
  '/commerce/': typeof CommerceIndexRoute
  '/globals/': typeof GlobalsIndexRoute
  '/collections/$slug/$entryId': typeof CollectionsSlugEntryIdRoute
  '/commerce/$slug/$entryId': typeof CommerceSlugEntryIdRoute
  '/collections/$slug/': typeof CollectionsSlugIndexRoute
  '/commerce/$slug/': typeof CommerceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/media': typeof MediaRoute
  '/users': typeof UsersRoute
  '/extensions/$extensionPath': typeof ExtensionsExtensionPathRoute
  '/globals/$slug': typeof GlobalsSlugRoute
  '/globals/new': typeof GlobalsNewRoute
  '/collections': typeof CollectionsIndexRoute
  '/commerce': typeof CommerceIndexRoute
  '/globals': typeof GlobalsIndexRoute
  '/collections/$slug/$entryId': typeof CollectionsSlugEntryIdRoute
  '/commerce/$slug/$entryId': typeof CommerceSlugEntryIdRoute
  '/collections/$slug': typeof CollectionsSlugIndexRoute
  '/commerce/$slug': typeof CommerceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/commerce': typeof CommerceRouteWithChildren
  '/globals': typeof GlobalsRouteWithChildren
  '/media': typeof MediaRoute
  '/users': typeof UsersRoute
  '/extensions/$extensionPath': typeof ExtensionsExtensionPathRoute
  '/globals/$slug': typeof GlobalsSlugRoute
  '/globals/new': typeof GlobalsNewRoute
  '/collections/': typeof CollectionsIndexRoute
  '/commerce/': typeof CommerceIndexRoute
  '/globals/': typeof GlobalsIndexRoute
  '/collections/$slug/$entryId': typeof CollectionsSlugEntryIdRoute
  '/commerce/$slug/$entryId': typeof CommerceSlugEntryIdRoute
  '/collections/$slug/': typeof CollectionsSlugIndexRoute
  '/commerce/$slug/': typeof CommerceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/collections'
    | '/commerce'
    | '/globals'
    | '/media'
    | '/users'
    | '/extensions/$extensionPath'
    | '/globals/$slug'
    | '/globals/new'
    | '/collections/'
    | '/commerce/'
    | '/globals/'
    | '/collections/$slug/$entryId'
    | '/commerce/$slug/$entryId'
    | '/collections/$slug/'
    | '/commerce/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/media'
    | '/users'
    | '/extensions/$extensionPath'
    | '/globals/$slug'
    | '/globals/new'
    | '/collections'
    | '/commerce'
    | '/globals'
    | '/collections/$slug/$entryId'
    | '/commerce/$slug/$entryId'
    | '/collections/$slug'
    | '/commerce/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/collections'
    | '/commerce'
    | '/globals'
    | '/media'
    | '/users'
    | '/extensions/$extensionPath'
    | '/globals/$slug'
    | '/globals/new'
    | '/collections/'
    | '/commerce/'
    | '/globals/'
    | '/collections/$slug/$entryId'
    | '/commerce/$slug/$entryId'
    | '/collections/$slug/'
    | '/commerce/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  CommerceRoute: typeof CommerceRouteWithChildren
  GlobalsRoute: typeof GlobalsRouteWithChildren
  MediaRoute: typeof MediaRoute
  UsersRoute: typeof UsersRoute
  ExtensionsExtensionPathRoute: typeof ExtensionsExtensionPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globals': {
      id: '/globals'
      path: '/globals'
      fullPath: '/globals'
      preLoaderRoute: typeof GlobalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/commerce/': {
      id: '/commerce/'
      path: '/'
      fullPath: '/commerce/'
      preLoaderRoute: typeof CommerceIndexRouteImport
      parentRoute: typeof CommerceRoute
    }
    '/extensions/$extensionPath': {
      id: '/extensions/$extensionPath'
      path: '/extensions/$extensionPath'
      fullPath: '/extensions/$extensionPath'
      preLoaderRoute: typeof ExtensionsExtensionPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/globals/': {
      id: '/globals/'
      path: '/'
      fullPath: '/globals/'
      preLoaderRoute: typeof GlobalsIndexRouteImport
      parentRoute: typeof GlobalsRoute
    }
    '/globals/$slug': {
      id: '/globals/$slug'
      path: '/$slug'
      fullPath: '/globals/$slug'
      preLoaderRoute: typeof GlobalsSlugRouteImport
      parentRoute: typeof GlobalsRoute
    }
    '/globals/new': {
      id: '/globals/new'
      path: '/new'
      fullPath: '/globals/new'
      preLoaderRoute: typeof GlobalsNewRouteImport
      parentRoute: typeof GlobalsRoute
    }
    '/collections/$slug/': {
      id: '/collections/$slug/'
      path: '/$slug'
      fullPath: '/collections/$slug/'
      preLoaderRoute: typeof CollectionsSlugIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/$slug/$entryId': {
      id: '/collections/$slug/$entryId'
      path: '/$slug/$entryId'
      fullPath: '/collections/$slug/$entryId'
      preLoaderRoute: typeof CollectionsSlugEntryIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/commerce/$slug/': {
      id: '/commerce/$slug/'
      path: '/$slug'
      fullPath: '/commerce/$slug/'
      preLoaderRoute: typeof CommerceSlugIndexRouteImport
      parentRoute: typeof CommerceRoute
    }
    '/commerce/$slug/$entryId': {
      id: '/commerce/$slug/$entryId'
      path: '/$slug/$entryId'
      fullPath: '/commerce/$slug/$entryId'
      preLoaderRoute: typeof CommerceSlugEntryIdRouteImport
      parentRoute: typeof CommerceRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsSlugEntryIdRoute: typeof CollectionsSlugEntryIdRoute
  CollectionsSlugIndexRoute: typeof CollectionsSlugIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsSlugEntryIdRoute: CollectionsSlugEntryIdRoute,
  CollectionsSlugIndexRoute: CollectionsSlugIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface CommerceRouteChildren {
  CommerceIndexRoute: typeof CommerceIndexRoute
  CommerceSlugEntryIdRoute: typeof CommerceSlugEntryIdRoute
  CommerceSlugIndexRoute: typeof CommerceSlugIndexRoute
}

const CommerceRouteChildren: CommerceRouteChildren = {
  CommerceIndexRoute: CommerceIndexRoute,
  CommerceSlugEntryIdRoute: CommerceSlugEntryIdRoute,
  CommerceSlugIndexRoute: CommerceSlugIndexRoute,
}

const CommerceRouteWithChildren = CommerceRoute._addFileChildren(
  CommerceRouteChildren,
)

interface GlobalsRouteChildren {
  GlobalsSlugRoute: typeof GlobalsSlugRoute
  GlobalsNewRoute: typeof GlobalsNewRoute
  GlobalsIndexRoute: typeof GlobalsIndexRoute
}

const GlobalsRouteChildren: GlobalsRouteChildren = {
  GlobalsSlugRoute: GlobalsSlugRoute,
  GlobalsNewRoute: GlobalsNewRoute,
  GlobalsIndexRoute: GlobalsIndexRoute,
}

const GlobalsRouteWithChildren =
  GlobalsRoute._addFileChildren(GlobalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  CommerceRoute: CommerceRouteWithChildren,
  GlobalsRoute: GlobalsRouteWithChildren,
  MediaRoute: MediaRoute,
  UsersRoute: UsersRoute,
  ExtensionsExtensionPathRoute: ExtensionsExtensionPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
